name: "Docker Build & Push"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      image_tag_version:
        description: "Version of image tag (after ':')"
        required: true

jobs:
  export_tag:
    name: "Generate Docker image tag"
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.image_tag.outputs.image_tag }}
    env:
      IMAGE_TAG_PACKAGE_NAME: portforward
    steps:
      - name: "Lowercase GitHub user"
        id: lowercase_repo
        run: |
          echo "GH_USER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
      - name: "Set IMAGE_TAG_BASE and IMAGE_TAG_VERSION_FILE"
        run: |
          echo "IMAGE_TAG_BASE=ghcr.io/${{ env.GH_USER }}/${{ env.IMAGE_TAG_PACKAGE_NAME }}" >> $GITHUB_ENV
          echo "IMAGE_TAG_VERSION_FILE=/tmp/image_tag_version.txt" >> $GITHUB_ENV
      - name: "Identify image tag version (from push to main)"
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "latest" > ${{ env.IMAGE_TAG_VERSION_FILE }}
      - name: "Set image tag version (from workflow dispatch)"
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.image_tag_version }}
        run: echo ${{ github.event.inputs.image_tag_version }} > ${{ env.IMAGE_TAG_VERSION_FILE }}
      - name: "Fetch exported image tag version"
        id: image_tag_version
        uses: juliangruber/read-file-action@v1
        with:
          path: ${{ env.IMAGE_TAG_VERSION_FILE }}
      - name: "Format complete image tag"
        id: image_tag
        run: |
          FULL_TAG="${{ env.IMAGE_TAG_BASE }}:${{ steps.image_tag_version.outputs.content }}"
          echo "Full tag: $FULL_TAG"
          echo "::set-output name=image_tag::$FULL_TAG"
  
  build_push:
    name: "Docker Build & Push"
    runs-on: ubuntu-latest
    needs: export_tag
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build and push"
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          push: true
          tags: ${{ needs.export_tag.outputs.image_tag }}