name: "Run tests"
on:
  push:
    branches:
      - '**'
  workflow_dispatch: {}

jobs:
  test:
    name: "Run tests"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: "Install go"
        uses: actions/setup-go@v2
        with:
          stable: true
          go-version: "1.17"
      - name: "Run unit tests"
        run: make test-unit
      - name: "Build Docker image"
        run: make build
      - name: "Run integration tests"
        run: make test-integration
