name: "Run tests"
on:
  push:
    branches:
      - '*'
  workflow_dispatch: {}

jobs:
  test:
    name: "Run tests"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@master
        with:
          fetch-depth: 1
